/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        // Legacy compat
        background: "#000000",
        foreground: "#e5e2e3",
        "primary-foreground": "var(--bg-primary)",
        "accent-2": "var(--accent-2)",
        teal: "var(--teal)",
        card: "var(--bg-panel)",
        "card-foreground": "var(--text-primary)",
        border: "var(--border-primary)",
        input: "var(--bg-input)",
        ring: "var(--accent)",
        muted: "var(--text-muted)",
        "muted-foreground": "var(--text-secondary)",
        destructive: "var(--danger)",

        // Cyber-Urban design tokens
        "accent-cyan": "#00f4fe",
        surface: "#131314",
        "surface-main": "#0a0a0b",
        "surface-dim": "#131314",
        "surface-bright": "#3a393a",
        "surface-variant": "#353436",
        "surface-container-lowest": "#0e0e0f",
        "surface-container-low": "#1c1b1c",
        "surface-container": "#201f20",
        "surface-container-high": "#2a2a2b",
        "surface-container-highest": "#353436",
        "surface-tint": "#ffade0",

        "on-surface": "#e5e2e3",
        "on-surface-variant": "#debece",
        "on-background": "#e5e2e3",
        outline: "#a68998",
        "outline-variant": "#57404e",

        "accent-pink": "#ffade0",
        "accent-gold": "#b8d300",
        "accent-teal": "#00f4fe",

        primary: "#ffade0",
        "primary-container": "#ff32d0",
        "on-primary": "#60004c",
        "on-primary-container": "#540043",
        "primary-fixed": "#ffd8ed",
        "primary-fixed-dim": "#ffade0",
        "on-primary-fixed": "#3b002e",
        "on-primary-fixed-variant": "#87006d",

        secondary: "#e6feff",
        "secondary-container": "#00f4fe",
        "on-secondary": "#003739",
        "on-secondary-container": "#006c71",
        "secondary-fixed": "#63f7ff",
        "secondary-fixed-dim": "#00dce5",
        "on-secondary-fixed": "#002021",
        "on-secondary-fixed-variant": "#004f53",

        tertiary: "#b8d300",
        "tertiary-fixed": "#d2f100",
        "tertiary-fixed-dim": "#b8d300",
        "tertiary-container": "#869a00",
        "on-tertiary": "#2c3400",
        "on-tertiary-container": "#262d00",
        "on-tertiary-fixed": "#191e00",
        "on-tertiary-fixed-variant": "#414c00",

        error: "#ffb4ab",
        "error-container": "#93000a",
        "on-error": "#690005",
        "on-error-container": "#ffdad6",

        "inverse-surface": "#e5e2e3",
        "inverse-on-surface": "#313031",
        "inverse-primary": "#b0008f",
      },
      fontFamily: {
        display: ["Geist Variable", "system-ui", "sans-serif"],
        mono: ["JetBrains Mono Variable", "Fira Code", "monospace"],
        hand: ["Architects Daughter", "cursive"],
        // Typographic role aliases — all resolve to the variable Geist face
        "label-md": ["Geist Variable", "system-ui", "sans-serif"],
        "label-sm": ["Geist Variable", "system-ui", "sans-serif"],
        "code-sm": ["JetBrains Mono Variable", "Fira Code", "monospace"],
        "headline-md": ["Geist Variable", "system-ui", "sans-serif"],
        "headline-lg": ["Geist Variable", "system-ui", "sans-serif"],
        "body-md": ["Geist Variable", "system-ui", "sans-serif"],
        "body-sm": ["Geist Variable", "system-ui", "sans-serif"],
        "data-micro": ["Geist Variable", "system-ui", "sans-serif"],
      },
      fontSize: {
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.02em", fontWeight: "500" }],
        "label-sm": ["10px", { lineHeight: "14px", letterSpacing: "0.05em", fontWeight: "500" }],
        "code-sm": ["11px", { lineHeight: "16px", fontWeight: "400" }],
        "headline-md": ["20px", { lineHeight: "26px", fontWeight: "600" }],
        "headline-lg": ["28px", { lineHeight: "36px", letterSpacing: "0.05em", fontWeight: "800" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "body-sm": ["12px", { lineHeight: "16px", fontWeight: "400" }],
        "data-micro": ["8px", { lineHeight: "10px", fontWeight: "700" }],
      },
      spacing: {
        "container-padding": "1rem",
        "panel-gap": "0.5rem",
        "sidebar-width": "320px",
        "timeline-height": "180px",
        "header-height": "56px",
        "element-gap": "0.5rem",
      },
      borderRadius: {
        sm: "2px",
        DEFAULT: "4px",
        md: "6px",
        lg: "8px",
        xl: "12px",
        "2xl": "16px",
        full: "9999px",
      },
      animation: {
        "fade-in": "fadeIn 0.2s ease-in-out",
        "slide-up": "slideUp 0.3s ease-out",
        "pulse-glow": "pulseGlow 2s infinite ease-in-out",
        shimmer: "shimmer 1.5s infinite ease-in-out",
        scanline: "scanline 3s linear infinite",
      },
      keyframes: {
        fadeIn: {
          "0%": { opacity: "0" },
          "100%": { opacity: "1" },
        },
        slideUp: {
          "0%": { opacity: "0", transform: "translateY(10px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        pulseGlow: {
          "0%": { boxShadow: "0 0 5px rgba(255,0,127,0.4)", opacity: "0.8" },
          "50%": { boxShadow: "0 0 20px rgba(255,223,0,0.8)", opacity: "1" },
          "100%": { boxShadow: "0 0 5px rgba(255,0,127,0.4)", opacity: "0.8" },
        },
        shimmer: {
          "0%": { opacity: "0.5", filter: "drop-shadow(0 0 2px rgba(255,0,127,0.5))" },
          "50%": { opacity: "1", filter: "drop-shadow(0 0 8px rgba(255,223,0,0.8))" },
          "100%": { opacity: "0.5", filter: "drop-shadow(0 0 2px rgba(255,0,127,0.5))" },
        },
        scanline: {
          "0%": { top: "0%" },
          "100%": { top: "100%" },
        },
      },
    },
  },
  plugins: [],
};
