/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        // Legacy compat
        background: "var(--background)",
        foreground: "var(--on-background)",
        "primary-foreground": "var(--bg-primary)",
        "accent-2": "var(--accent-2)",
        teal: "var(--teal)",
        card: "var(--bg-panel)",
        "card-foreground": "var(--text-primary)",
        border: "var(--border-primary)",
        input: "var(--bg-input)",
        ring: "var(--accent)",
        muted: "var(--text-muted)",
        "muted-foreground": "var(--text-secondary)",
        destructive: "var(--danger)",

        // Cyber-Urban design tokens
        "accent-cyan": "var(--teal)",
        surface: "var(--surface)",
        "surface-main": "var(--surface-main)",
        "surface-dim": "var(--surface-dim)",
        "surface-bright": "var(--surface-bright)",
        "surface-variant": "var(--surface-variant)",
        "surface-container-lowest": "var(--surface-container-lowest)",
        "surface-container-low": "var(--surface-container-low)",
        "surface-container": "var(--surface-container)",
        "surface-container-high": "var(--surface-container-high)",
        "surface-container-highest": "var(--surface-container-highest)",
        "surface-tint": "var(--surface-tint)",

        "on-surface": "var(--on-surface)",
        "on-surface-variant": "var(--on-surface-variant)",
        "on-background": "var(--on-background)",
        outline: "var(--outline)",
        "outline-variant": "var(--outline-variant)",

        "accent-pink": "var(--accent-pink)",
        "accent-gold": "var(--accent-gold)",
        "accent-teal": "var(--accent-teal)",

        primary: "var(--primary)",
        "primary-container": "var(--primary-container)",
        "on-primary": "var(--on-primary)",
        "on-primary-container": "var(--on-primary-container)",
        "primary-fixed": "var(--primary-fixed)",
        "primary-fixed-dim": "var(--primary-fixed-dim)",
        "on-primary-fixed": "var(--on-primary-fixed)",
        "on-primary-fixed-variant": "var(--on-primary-fixed-variant)",

        secondary: "var(--secondary)",
        "secondary-container": "var(--secondary-container)",
        "on-secondary": "var(--on-secondary)",
        "on-secondary-container": "var(--on-secondary-container)",
        "secondary-fixed": "var(--secondary-fixed)",
        "secondary-fixed-dim": "var(--secondary-fixed-dim)",
        "on-secondary-fixed": "var(--on-secondary-fixed)",
        "on-secondary-fixed-variant": "var(--on-secondary-fixed-variant)",

        tertiary: "var(--tertiary)",
        "tertiary-fixed": "var(--tertiary-fixed)",
        "tertiary-fixed-dim": "var(--tertiary-fixed-dim)",
        "tertiary-container": "var(--tertiary-container)",
        "on-tertiary": "var(--on-tertiary)",
        "on-tertiary-container": "var(--on-tertiary-container)",
        "on-tertiary-fixed": "var(--on-tertiary-fixed)",
        "on-tertiary-fixed-variant": "var(--on-tertiary-fixed-variant)",

        error: "var(--danger)",
        "error-container": "var(--error-container)",
        "on-error": "var(--on-error)",
        "on-error-container": "var(--on-error-container)",

        "inverse-surface": "var(--inverse-surface)",
        "inverse-on-surface": "var(--inverse-on-surface)",
        "inverse-primary": "var(--inverse-primary)",
      },
      fontFamily: {
        display: ["Geist Variable", "system-ui", "sans-serif"],
        mono: ["JetBrains Mono Variable", "Fira Code", "monospace"],
        hand: ["Architects Daughter", "cursive"],
        // Typographic role aliases — all resolve to the variable Geist face
        "label-md": ["Geist Variable", "system-ui", "sans-serif"],
        "label-sm": ["Geist Variable", "system-ui", "sans-serif"],
        "code-sm": ["JetBrains Mono Variable", "Fira Code", "monospace"],
        "headline-md": ["Geist Variable", "system-ui", "sans-serif"],
        "headline-lg": ["Geist Variable", "system-ui", "sans-serif"],
        "body-md": ["Geist Variable", "system-ui", "sans-serif"],
        "body-sm": ["Geist Variable", "system-ui", "sans-serif"],
        "data-micro": ["Geist Variable", "system-ui", "sans-serif"],
      },
      fontSize: {
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.02em", fontWeight: "500" }],
        "label-sm": ["10px", { lineHeight: "14px", letterSpacing: "0.05em", fontWeight: "500" }],
        "code-sm": ["11px", { lineHeight: "16px", fontWeight: "400" }],
        "headline-md": ["20px", { lineHeight: "26px", fontWeight: "600" }],
        "headline-lg": ["28px", { lineHeight: "36px", letterSpacing: "0.05em", fontWeight: "800" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "body-sm": ["12px", { lineHeight: "16px", fontWeight: "400" }],
        "data-micro": ["8px", { lineHeight: "10px", fontWeight: "700" }],
      },
      spacing: {
        "container-padding": "1rem",
        "panel-gap": "0.5rem",
        "sidebar-width": "320px",
        "timeline-height": "180px",
        "header-height": "56px",
        "element-gap": "0.5rem",
      },
      borderRadius: {
        sm: "2px",
        DEFAULT: "4px",
        md: "6px",
        lg: "8px",
        xl: "12px",
        "2xl": "16px",
        full: "9999px",
      },
      animation: {
        "fade-in": "fadeIn 0.2s ease-in-out",
        "slide-up": "slideUp 0.3s ease-out",
        "pulse-glow": "pulseGlow 2s infinite ease-in-out",
        shimmer: "shimmer 1.5s infinite ease-in-out",
        scanline: "scanline 3s linear infinite",
      },
      keyframes: {
        fadeIn: {
          "0%": { opacity: "0" },
          "100%": { opacity: "1" },
        },
        slideUp: {
          "0%": { opacity: "0", transform: "translateY(10px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        pulseGlow: {
          "0%": { boxShadow: "0 0 5px rgba(255,0,127,0.4)", opacity: "0.8" },
          "50%": { boxShadow: "0 0 20px rgba(255,223,0,0.8)", opacity: "1" },
          "100%": { boxShadow: "0 0 5px rgba(255,0,127,0.4)", opacity: "0.8" },
        },
        shimmer: {
          "0%": { opacity: "0.5", filter: "drop-shadow(0 0 2px rgba(255,0,127,0.5))" },
          "50%": { opacity: "1", filter: "drop-shadow(0 0 8px rgba(255,223,0,0.8))" },
          "100%": { opacity: "0.5", filter: "drop-shadow(0 0 2px rgba(255,0,127,0.5))" },
        },
        scanline: {
          "0%": { top: "0%" },
          "100%": { top: "100%" },
        },
      },
    },
  },
  plugins: [],
};
