import { create } from "zustand";
import type { AudioBakeData, AudioManifest } from "../engine/audio/types";
import { type WatermarkSettings, DEFAULT_WATERMARK } from "../utils/watermark";

/**
 * Composition guides available in the viewport. Each replaces a former
 * `overlay.*` registry effect of the same name.
 */
export interface ViewportGuides {
  safeArea: boolean;
  ruleOfThirds: boolean;
  crosshairs: boolean;
  pixelGrid: boolean;
}

export interface EffectMeta {
  id: string;
  name: string;
  category: string;
  media_type: string;
  parameters: ParameterDef[];
}

export interface ParameterDef {
  id: string;
  name: string;
  type: "slider" | "select" | "toggle" | "color" | "palette" | "mask" | "text";
  default: unknown;
  min?: number;
  max?: number;
  step?: number;
  options?: string[] | null;
}

export interface StackEntry {
  id: string; // unique instance id
  effectId: string;
  effectName: string;
  params: Record<string, unknown>;
  enabled: boolean;
  maskId: string | null; // null = no mask, "active" = global activeMask, "sam3-0" etc = SAM3 masks
  maskB64?: string | null; // snapshot of resolved mask data at assignment time
  maskMode: "inside" | "outside" | "alpha"; // how mask affects the effect
}

export interface AudioBinding {
  /** Which audio feature drives this parameter */
  source: string;
  inputMin: number;
  inputMax: number;
  outputMin: number;
  outputMax: number;
  attack: number;
  decay: number;
  gateEnabled: boolean;
  gateThreshold: number;
  invert: boolean;
}

export type EasingType = "linear" | "easeIn" | "easeOut" | "easeInOut" | "hold";

export type BlendMode =
  | "normal"
  | "multiply"
  | "screen"
  | "overlay"
  | "darken"
  | "lighten"
  | "color-dodge"
  | "color-burn"
  | "hard-light"
  | "soft-light"
  | "difference"
  | "exclusion";

export interface Track {
  id: string;
  name: string;
  visible: boolean;
  opacity: number; // 0-1
  blendMode: BlendMode;
  effectStack: StackEntry[];
  filePath: string | null;
}

export interface Keyframe {
  id: string;
  time: number;
  value: number;
  easing: EasingType;
}

/** Per-stack-entry-id, per-parameter-id keyframes */
export type KeyframeTrack = Record<string, Keyframe[]>;

export type AppTheme = "dark" | "high-contrast" | "light" | "cosmic" | "custom";

export interface AppState {
  // Timeline
  currentTime: number;
  setCurrentTime: (t: number) => void;
  isPlaying: boolean;
  togglePlay: () => void;
  stopPlayback: () => void;
  loopMode: "off" | "loop" | "pingpong";
  setLoopMode: (mode: "off" | "loop" | "pingpong") => void;
  duration: number;
  setDuration: (d: number) => void;
  inPoint: number | null;
  outPoint: number | null;
  setInPoint: (t: number | null) => void;
  setOutPoint: (t: number | null) => void;
  clearInOut: () => void;

  // Media
  mediaLoaded: boolean;
  mediaInfo: { width: number; height: number } | null;
  mediaMetadata: Record<string, unknown> | null;
  previewDataUrl: string | null;
  originalDataUrl: string | null;
  filePath: string | null;
  proxyUrl: string | null;
  isVideo: boolean;
  /** When true, preview uses CPU (Rust backend) instead of WebGL shaders.
   *  Set when the stack contains effects without accurate WebGL implementations
   *  (e.g. error diffusion dithering algorithms). */
  useCpuPreview: boolean;

  // Effects
  allEffects: EffectMeta[];
  activeCategory: string;
  searchQuery: string;
  effectStack: StackEntry[];
  pastStacks: StackEntry[][];
  futureStacks: StackEntry[][];
  selectedStackId: string | null;

  // Audio-Reactive
  audioEnabled: boolean;
  audioFilePath: string | null;
  audioPlaying: boolean;
  audioVolume: number;
  audioBpm: number | null;
  audioBandEnergies: Record<string, number>;
  audioBeatFlags: { bass: boolean; mid: boolean; treble: boolean };
  /** Per-stack-entry-id, per-parameter-id audio binding config */
  audioBindings: Record<string, Record<string, AudioBinding>>;
  /** Latest mapped audio values per channel name */
  audioMappedValues: Record<string, number>;
  /** Baked audio features for export parity. Generated by AudioFeatureExtractor. */
  audioBakeData: AudioBakeData | null;
  /** Audio manifest — the single source of truth for audio-reactive effects. */
  audioManifest: AudioManifest | null;
  /** Manifest analysis progress (0-1). */
  audioManifestProgress: number;
  /** Manifest analysis phase description. */
  audioManifestPhase: string;
  /** True when the loaded video's audio is silent or missing. The UI shows
   *  a warning banner so the user knows audio-reactive effects won't respond. */
  audioIsSilent: boolean;

  /**
   * Composition guides drawn on top of the preview and never exported.
   *
   * These were previously four entries in the effect registry
   * (`overlay.safe_area` and friends), which meant framing aids sat in the same
   * list as Datamosh and VHS and got burned into the delivered file. They are
   * viewport furniture, so they live in view state.
   */
  viewportGuides: ViewportGuides;

  // Mask / Segmentation
  activeMask: string | null; // base64 PNG of current mask
  maskRevision: number;
  maskVisible: boolean;
  maskTab: "sam3" | "manual";
  maskTool: "brush" | "eraser" | "rect" | "ellipse" | "polygon";
  brushSize: number;
  sam3Ready: boolean;
  /** Whether the CURRENT frame's image finished loading into SAM3 successfully.
   *  False (the default) until a load succeeds, and reset to false on a
   *  failed (re)load, so callers can gate point/box prompts on "the image
   *  currently loaded actually matches what's on screen" rather than just
   *  "the engine is running". */
  sam3ImageLoaded: boolean;
  sam3Mode: "text" | "point" | "box" | "auto";
  /** When true, the next left-click on the viewport fires a point prompt */
  sam3Clicking: boolean;

  // Tree masking — accumulated positive (1) and negative (0) point prompts
  sam3Points: Array<{ x: number; y: number; label: 1 | 0 }>;
  sam3HoverMask: string | null; // temporary hover preview mask
  sam3OverlayOpacity: number;
  sam3OverlayColor: string;

  // Multi-mask output from SAM3 (3 masks sorted by score, highest first)
  sam3Masks: string[]; // base64 PNG masks
  sam3MaskScores: number[]; // confidence scores
  sam3MaskIndex: number; // which of the 3 masks is currently selected
  sam3FrameMasks: Record<number, string>; // per-frame masks

  // Keyframes
  keyframes: Record<string, KeyframeTrack>;

  // UI
  isProcessing: boolean;
  showBeforeAfter: boolean;
  zoom: number;
  statusMessage: string;
  playbackSpeed: number;
  scopeMode: "none" | "histogram" | "waveform" | "rgb_parade";
  scopesVisible: boolean;
  panelVisibility: Record<string, boolean>;

  // Dock system
  dockedPanels: string[];
  setDockedPanels: (panels: string[]) => void;
  layoutTrigger: { action: "add" | "remove" | "reset"; panelId?: string; ts: number } | null;
  triggerLayoutAction: (action: "add" | "remove" | "reset", panelId?: string) => void;

  // Window edge snapping & AppBar docking
  edgeSnapEnabled: boolean;
  appBarDocked: boolean;
  appBarEdge: "left" | "right" | "top" | "bottom" | null;
  appBarSize: number;
  setEdgeSnapEnabled: (enabled: boolean) => void;
  setAppBarDocked: (docked: boolean, edge?: "left" | "right" | "top" | "bottom", size?: number) => void;

  // Theme
  theme: AppTheme;
  panelOpacity: number;
  customPrimary: string;
  customSecondary: string;
  customBg: string;
  customUiModalOpen: boolean;
  setCustomThemeColors: (primary: string, secondary: string, bg: string) => void;

  // Animate-as-video. Length and frame rate used when turning a still into a
  // clip. Clip length is a creative parameter for datamoshing -- how long an
  // I-frame's corruption smears for is a function of how many frames follow it
  // -- so these are user settings rather than the constants they used to be.
  // The still's path is kept so the conversion can be undone in-app; the file
  // itself is untouched, but without this the only way back was reopening it.
  animateDurationSecs: number;
  animateFps: number;
  animateSourceStillPath: string | null;
  animateDialogOpen: boolean;
  setAnimateDurationSecs: (v: number) => void;
  setAnimateFps: (v: number) => void;
  setAnimateSourceStillPath: (p: string | null) => void;
  setAnimateDialogOpen: (open: boolean) => void;
  setCustomUiModalOpen: (open: boolean) => void;

  // Output sizing
  aspectRatioLock: boolean;
  aspectRatio: number | null; // e.g. 16/9, 4/3, null = free

  // Proxy Media
  proxyEnabled: boolean;
  proxyPath: string | null;
  proxyMaxWidth: number;
  proxyCrf: number;
  proxyGenerating: boolean;

  // Multi-Track Layering
  tracks: Track[];
  activeTrackId: string | null;

  // Export
  exportProgress: number;
  exportIsRunning: boolean;
  exportCancelRequested: boolean;
  exportTriggerId: number; // incremented to trigger export from anywhere
  watermark: WatermarkSettings;

  // Actions
  setMediaLoaded: (loaded: boolean) => void;
  setMediaInfo: (info: { width: number; height: number } | null) => void;
  setMediaMetadata: (meta: Record<string, unknown> | null) => void;
  setPreviewDataUrl: (url: string | null) => void;
  setOriginalDataUrl: (url: string | null) => void;
  setFilePath: (path: string | null) => void;
  setProxyUrl: (url: string | null) => void;
  setIsVideo: (isVideo: boolean) => void;
  setUseCpuPreview: (v: boolean) => void;
  setAllEffects: (effects: EffectMeta[]) => void;
  setActiveCategory: (cat: string) => void;
  setSearchQuery: (q: string) => void;
  addToStack: (effect: EffectMeta) => void;
  setEffectStack: (stack: StackEntry[]) => void;
  addLUTEffect: (previewUrl: string, filePath?: string) => void;
  removeFromStack: (id: string) => void;
  moveStackItem: (fromIndex: number, toIndex: number) => void;
  updateStackParams: (id: string, params: Record<string, unknown>) => void;
  /** Update params without pushing to undo history (used by keyframe playback) */
  updateStackParamsSilent: (id: string, params: Record<string, unknown>) => void;
  setStackItemMask: (id: string, maskId: string | null) => void;
  setStackItemMaskMode: (id: string, mode: "inside" | "outside" | "alpha") => void;
  toggleStackItem: (id: string) => void;
  selectStackItem: (id: string | null) => void;
  setIsProcessing: (v: boolean) => void;
  setShowBeforeAfter: (v: boolean) => void;
  setZoom: (z: number) => void;
  setStatusMessage: (msg: string) => void;
  setPlaybackSpeed: (speed: number) => void;
  setScopeMode: (mode: "none" | "histogram" | "waveform" | "rgb_parade") => void;
  setScopesVisible: (v: boolean) => void;
  togglePanel: (id: string) => void;
  setPanelVisible: (id: string, visible: boolean) => void;
  setTheme: (theme: AppTheme) => void;
  toggleTheme: () => void;
  setPanelOpacity: (v: number) => void;
  setAspectRatioLock: (v: boolean) => void;
  setAspectRatio: (ratio: number | null) => void;
  setExportProgress: (progress: number) => void;
  setExportIsRunning: (v: boolean) => void;
  requestExportCancel: () => void;
  triggerExport: () => void;
  resetExport: () => void;
  setWatermark: (settings: Partial<WatermarkSettings>) => void;
  clearStack: () => void;
  replaceStack: (stack: StackEntry[]) => void;
  undo: () => void;
  redo: () => void;
  canUndo: () => boolean;
  canRedo: () => boolean;

  // Audio actions
  setAudioEnabled: (v: boolean) => void;
  setAudioFilePath: (path: string | null) => void;
  setAudioPlaying: (v: boolean) => void;
  setAudioVolume: (v: number) => void;
  setAudioBpm: (bpm: number | null) => void;
  setAudioBandEnergies: (bands: Record<string, number>) => void;
  setAudioBeatFlags: (flags: { bass: boolean; mid: boolean; treble: boolean }) => void;
  setAudioBinding: (stackId: string, paramId: string, binding: AudioBinding | null) => void;
  setAudioBindings: (bindings: Record<string, Record<string, AudioBinding>>) => void;
  setAudioMappedValues: (values: Record<string, number>) => void;
  setAudioBakeData: (data: AudioBakeData | null) => void;
  setAudioManifest: (manifest: AudioManifest | null) => void;
  setAudioManifestProgress: (progress: number, phase: string) => void;
  setAudioIsSilent: (silent: boolean) => void;

  // Keyframe actions
  addKeyframe: (stackId: string, paramId: string, keyframe: Keyframe) => void;
  removeKeyframe: (stackId: string, paramId: string, keyframeId: string) => void;
  updateKeyframe: (
    stackId: string,
    paramId: string,
    keyframeId: string,
    patch: Partial<Keyframe>
  ) => void;
  setKeyframesForTrack: (stackId: string, paramId: string, keyframes: Keyframe[]) => void;
  setKeyframes: (keyframes: Record<string, KeyframeTrack>) => void;
  clearKeyframes: (stackId?: string, paramId?: string) => void;
  getKeyframeValue: (stackId: string, paramId: string, time: number) => number | null;

  // Mask actions
  setActiveMask: (maskB64: string | null) => void;
  setMaskVisible: (v: boolean) => void;
  toggleViewportGuide: (guide: keyof ViewportGuides) => void;
  setViewportGuides: (guides: Partial<ViewportGuides>) => void;
  setMaskTab: (tab: "sam3" | "manual") => void;
  setMaskTool: (tool: "brush" | "eraser" | "rect" | "ellipse" | "polygon") => void;
  setBrushSize: (size: number) => void;
  setSam3Ready: (v: boolean) => void;
  setSam3ImageLoaded: (v: boolean) => void;
  setSam3Mode: (mode: "text" | "point" | "box" | "auto") => void;
  setSam3Clicking: (v: boolean) => void;

  // Tree masking actions
  addSam3Point: (point: { x: number; y: number; label: 1 | 0 }) => void;
  removeSam3Point: (index: number) => void;
  clearSam3Points: () => void;
  setSam3HoverMask: (mask: string | null) => void;
  setSam3OverlayOpacity: (v: number) => void;
  setSam3OverlayColor: (color: string) => void;

  // Multi-mask actions
  setSam3Masks: (masks: string[], scores: number[]) => void;
  setSam3MaskIndex: (index: number) => void;
  setSam3FrameMasks: (masks: Record<number, string>) => void;
  clearSam3FrameMasks: () => void;

  // Proxy actions
  setProxyEnabled: (v: boolean) => void;
  setProxyPath: (path: string | null) => void;
  setProxyMaxWidth: (w: number) => void;
  setProxyCrf: (crf: number) => void;
  setProxyGenerating: (v: boolean) => void;

  // Track actions
  addTrack: (name?: string) => string;
  removeTrack: (id: string) => void;
  renameTrack: (id: string, name: string) => void;
  setActiveTrack: (id: string | null) => void;
  setTrackVisible: (id: string, visible: boolean) => void;
  setTrackOpacity: (id: string, opacity: number) => void;
  setTrackBlendMode: (id: string, mode: BlendMode) => void;
  moveTrack: (fromIndex: number, toIndex: number) => void;
  getActiveTrack: () => Track | null;
}

let instanceIdCounter = 0;

/** Generate a unique stack entry ID that survives HMR reloads */
function nextStackId(prefix = "stack"): string {
  instanceIdCounter += 1;
  // Use crypto.randomUUID when available for true uniqueness,
  // falling back to timestamp + counter for environments without it
  const suffix = typeof crypto !== "undefined" && crypto.randomUUID
    ? crypto.randomUUID().slice(0, 8)
    : `${Date.now()}-${instanceIdCounter}`;
  return `${prefix}-${suffix}`;
}


/** Clamp a value to [min, max], returning fallback for NaN */
function clampFinite(value: number, min: number, max: number, fallback: number): number {
  if (Number.isNaN(value)) return fallback;
  return Math.max(min, Math.min(max, value));
}

/** Remove NaN/Infinity numeric entries from a params object to prevent shader corruption */
function sanitizeParams(params: Record<string, unknown>): Record<string, unknown> {
  const out: Record<string, unknown> = {};
  for (const [k, v] of Object.entries(params)) {
    if (typeof v === "number" && !Number.isFinite(v)) continue;
    out[k] = v;
  }
  return out;
}

/**
 * Cap on retained undo-history entries. Each entry is a full snapshot of
 * effectStack; without a bound, a long editing session -- especially one
 * with many rapid parameter-drag ticks -- would retain an ever-growing
 * number of full-stack snapshots for the app's entire lifetime. `undo()`
 * and `redo()` move entries between pastStacks/futureStacks but never grow
 * the total beyond what pushHistory already capped, so this one bound is
 * sufficient for both arrays.
 */
const MAX_HISTORY_ENTRIES = 100;

/**
 * Snapshot the current effect stack onto the undo history and clear the
 * redo stack, for actions that make a new edit. Spread this into a `set()`
 * return value alongside that action's own state changes. Not used by
 * `redo()`, which has different semantics: it shifts (not clears)
 * `futureStacks` and pushes onto `pastStacks` from the *incoming* stack,
 * not the outgoing one.
 */
function pushHistory(state: Pick<AppState, "pastStacks" | "effectStack">) {
  const pastStacks = [...state.pastStacks, state.effectStack];
  return {
    pastStacks:
      pastStacks.length > MAX_HISTORY_ENTRIES
        ? pastStacks.slice(pastStacks.length - MAX_HISTORY_ENTRIES)
        : pastStacks,
    futureStacks: [] as StackEntry[][],
  };
}

export const useAppStore = create<AppState>((set, get) => ({
  currentTime: 0,
  isPlaying: true,
  loopMode: "off",
  duration: 10,
  mediaLoaded: false,
  mediaInfo: null,
  mediaMetadata: null,
  previewDataUrl: null,
  originalDataUrl: null,
  filePath: null,
  proxyUrl: null,
  isVideo: false,
  useCpuPreview: false,
  allEffects: [],
  activeCategory: "dithering",
  searchQuery: "",
  effectStack: [],
  pastStacks: [],
  futureStacks: [],
  selectedStackId: null,
  audioEnabled: false,
  audioFilePath: null,
  audioPlaying: false,
  audioVolume: 1,
  audioBpm: null,
  audioBandEnergies: {},
  audioBeatFlags: { bass: false, mid: false, treble: false },
  audioBindings: {},
  audioMappedValues: {},
  audioBakeData: null,
  audioManifest: null,
  audioManifestProgress: 0,
  audioManifestPhase: "",
  audioIsSilent: false,
  isProcessing: false,
  showBeforeAfter: false,
  zoom: 1,
  statusMessage: "Ready",
  playbackSpeed: 1,
  scopeMode: "none",
  scopesVisible: false,
  panelVisibility: {
    browser: true,
    preview: true,
    stack: true,
    audio: true,
    export: true,
    presets: true,
    mask: true,
    lut: true,
    proxy: true,
    tracks: true,
    // Verify runs the internal effect-registry self-test suite -- a QA/dev
    // tool for confirming the app's own effects work, not a content-creation
    // feature. Hidden from the panel rail so it doesn't compete for space
    // with the tools an end user actually needs day to day.
    verify: false,
  } as Record<string, boolean>,
  dockedPanels: [],
  layoutTrigger: null,
  edgeSnapEnabled: true,
  appBarDocked: false,
  appBarEdge: null,
  appBarSize: 300,
  theme: "dark",
  panelOpacity: 0.65,
  animateDurationSecs: 5,
  animateFps: 30,
  animateSourceStillPath: null,
  animateDialogOpen: false,
  customPrimary: "#00f4fe",
  customSecondary: "#ffade0",
  customBg: "#131314",
  customUiModalOpen: false,
  aspectRatioLock: false,
  aspectRatio: null,
  proxyEnabled: false,
  proxyPath: null,
  proxyMaxWidth: 1280,
  proxyCrf: 28,
  proxyGenerating: false,
  tracks: [],
  activeTrackId: null,
  inPoint: null,
  outPoint: null,
  activeMask: null,
  maskRevision: 0,
  maskVisible: true,
  viewportGuides: {
    safeArea: false,
    ruleOfThirds: false,
    crosshairs: false,
    pixelGrid: false,
  },
  maskTab: "sam3",
  maskTool: "brush",
  brushSize: 20,
  sam3Ready: false,
  sam3ImageLoaded: false,
  sam3Mode: "text",
  sam3Clicking: false,
  sam3Points: [],
  sam3HoverMask: null,
  sam3OverlayOpacity: 0.45,
  sam3OverlayColor: "#00ffff",
  sam3Masks: [],
  sam3MaskScores: [],
  sam3MaskIndex: 0,
  sam3FrameMasks: {},
  keyframes: {},
  exportProgress: 0,
  exportIsRunning: false,
  exportCancelRequested: false,
  exportTriggerId: 0,
  watermark: DEFAULT_WATERMARK,

  // Guarded like setDuration/setInPoint/setOutPoint, which this alone was
  // missing. currentTime reaches shader uniforms (PreviewViewport passes it as
  // animTime) and indexes sam3FrameMasks, so a NaN or Infinity here corrupts
  // the render silently rather than throwing.
  //
  // Only the lower bound is enforced here, not `duration`: duration is set
  // asynchronously while media loads, so clamping to it would truncate a seek
  // that arrives before the real duration does. The upper bound belongs at the
  // call sites that actually know it -- the playback loop already wraps to 0
  // before calling this.
  setCurrentTime: (t) =>
    set({ currentTime: Number.isFinite(t) ? Math.max(0, t) : 0 }),
  togglePlay: () => set((state) => ({ isPlaying: !state.isPlaying })),
  stopPlayback: () => set({ isPlaying: false }),
  setLoopMode: (mode) => set({ loopMode: mode }),
  setDuration: (d) => set({ duration: Math.max(0.1, d) }),
  setMediaLoaded: (loaded) => set({ mediaLoaded: loaded }),
  setMediaInfo: (info) => set({ mediaInfo: info }),
  setMediaMetadata: (meta) => set({ mediaMetadata: meta }),
  setPreviewDataUrl: (url) => set({ previewDataUrl: url }),
  setOriginalDataUrl: (url) => set({ originalDataUrl: url }),
  setFilePath: (path) => set({ filePath: path }),
  setProxyUrl: (url) => set({ proxyUrl: url }),
  setIsVideo: (isVideo) => set({ isVideo }),
  setUseCpuPreview: (v) => set({ useCpuPreview: v }),
  setAllEffects: (effects) => set({ allEffects: effects }),
  setActiveCategory: (cat) => set({ activeCategory: cat }),
  setSearchQuery: (q) => set({ searchQuery: q }),

  addToStack: (effect) => {
    const defaults: Record<string, unknown> = {};
    const params = effect.parameters ?? [];
    for (const p of params) {
      defaults[p.id] = p.default;
    }
    const entry: StackEntry = {
      id: nextStackId(),
      effectId: effect.id,
      effectName: effect.name,
      params: defaults,
      enabled: true,
      maskId: null,
      maskB64: null,
      maskMode: "inside",
    };
    set((state) => ({
      ...pushHistory(state),
      effectStack: [...state.effectStack, entry],
      selectedStackId: entry.id,
    }));
  },

  addLUTEffect: (previewUrl, filePath) => {
    const state = get();
    const effect = state.allEffects.find((e) => e.id === "color.lut_grading");
    const defaults: Record<string, unknown> = { amount: 1.0 };
    if (effect) {
      for (const p of effect.parameters) {
        defaults[p.id] = p.default;
      }
    }
    // filePath is used by the Rust export path; for bundled presets it is the
    // web-style URL with the leading slash removed. Custom user LUTs pass the
    // absolute disk path instead.
    const lut_path = filePath ?? previewUrl.replace(/^\//, "");
    const entry: StackEntry = {
      id: nextStackId(),
      effectId: "color.lut_grading",
      effectName: effect?.name ?? "LUT Color Grading",
      params: { ...defaults, tLUT: previewUrl, lut_path },
      enabled: true,
      maskId: null,
      maskB64: null,
      maskMode: "inside",
    };
    set((s) => ({
      ...pushHistory(s),
      effectStack: [...s.effectStack, entry],
      selectedStackId: entry.id,
    }));
  },

  removeFromStack: (id) =>
    set((state) => {
      const newStack = state.effectStack.filter((e) => e.id !== id);
      return {
        ...pushHistory(state),
        effectStack: newStack,
        selectedStackId:
          state.selectedStackId === id
            ? (newStack[newStack.length - 1]?.id ?? null)
            : state.selectedStackId,
      };
    }),

  setEffectStack: (stack) =>
    set((state) => ({
      ...pushHistory(state),
      effectStack: stack,
      selectedStackId: stack.length > 0 ? stack[stack.length - 1].id : null,
    })),

  moveStackItem: (fromIndex, toIndex) =>
    set((state) => {
      if (
        fromIndex < 0 ||
        fromIndex >= state.effectStack.length ||
        toIndex < 0 ||
        toIndex >= state.effectStack.length
      )
        return {};
      const arr = [...state.effectStack];
      const [item] = arr.splice(fromIndex, 1);
      arr.splice(toIndex, 0, item);
      return {
        ...pushHistory(state),
        effectStack: arr,
      };
    }),

  updateStackParams: (id, params) =>
    set((state) => ({
      ...pushHistory(state),
      effectStack: state.effectStack.map((e) =>
        e.id === id ? { ...e, params: { ...e.params, ...sanitizeParams(params) } } : e
      ),
    })),
  updateStackParamsSilent: (id, params) =>
    set((state) => ({
      effectStack: state.effectStack.map((e) =>
        e.id === id ? { ...e, params: { ...e.params, ...sanitizeParams(params) } } : e
      ),
    })),

  setStackItemMask: (id, maskId) =>
    set((state) => {
      // Snapshot the actual mask data at assignment time so it survives
      // future SAM3 runs that replace sam3Masks.
      let maskB64: string | null = null;
      if (maskId === "active") {
        maskB64 = state.activeMask;
      } else if (maskId && maskId.startsWith("sam3-")) {
        const idx = Number.parseInt(maskId.replace("sam3-", ""), 10);
        maskB64 = state.sam3Masks[idx] ?? null;
      }
      return {
        ...pushHistory(state),
        maskRevision: state.maskRevision + 1,
        effectStack: state.effectStack.map((e) => (e.id === id ? { ...e, maskId, maskB64 } : e)),
      };
    }),

  setStackItemMaskMode: (id, mode) =>
    set((state) => ({
      ...pushHistory(state),
      effectStack: state.effectStack.map((e) => (e.id === id ? { ...e, maskMode: mode } : e)),
    })),

  toggleStackItem: (id) =>
    set((state) => ({
      ...pushHistory(state),
      effectStack: state.effectStack.map((e) => (e.id === id ? { ...e, enabled: !e.enabled } : e)),
    })),

  selectStackItem: (id) => set({ selectedStackId: id }),
  setIsProcessing: (v) => set({ isProcessing: v }),
  setShowBeforeAfter: (v) => set({ showBeforeAfter: v }),
  setZoom: (z) => set({ zoom: clampFinite(z, 0.1, 5, 1) }),
  setStatusMessage: (msg) => set({ statusMessage: msg }),
  setPlaybackSpeed: (speed) => set({ playbackSpeed: clampFinite(speed, 0.25, 4, 1) }),
  setScopeMode: (mode) => set({ scopeMode: mode }),
  setScopesVisible: (v) => set({ scopesVisible: v }),
  togglePanel: (id) =>
    set((state) => ({
      panelVisibility: { ...state.panelVisibility, [id]: !state.panelVisibility[id] },
    })),
  setPanelVisible: (id, visible) =>
    set((state) => ({
      panelVisibility: { ...state.panelVisibility, [id]: visible },
    })),

  // ── Dock system actions ──
  setDockedPanels: (panels) => set({ dockedPanels: panels }),
  triggerLayoutAction: (action, panelId) => set({ layoutTrigger: { action, panelId, ts: Date.now() } }),
  setEdgeSnapEnabled: (enabled) => set({ edgeSnapEnabled: enabled }),
  setAppBarDocked: (docked, edge, size) =>
    set((state) => ({
      appBarDocked: docked,
      appBarEdge: docked ? (edge ?? null) : null,
      appBarSize: size ?? state.appBarSize,
    })),
  setTheme: (theme) => set({ theme }),
  toggleTheme: () => set((state) => ({ theme: state.theme === "dark" ? "light" : "dark" })),
  setPanelOpacity: (v) => set({ panelOpacity: Math.max(0.2, Math.min(1, v)) }),
  // Clamped rather than validated at the call site so a bad value cannot reach
  // ffmpeg's -t/-r. The ceilings are practical, not technical: a still expands
  // to duration*fps identical frames, so 120s at 120fps is already 14400 frames
  // of freeze-frame before any effect runs.
  setAnimateDurationSecs: (v) =>
    set({ animateDurationSecs: Number.isFinite(v) ? Math.max(0.1, Math.min(120, v)) : 5 }),
  setAnimateFps: (v) =>
    set({ animateFps: Number.isFinite(v) ? Math.max(1, Math.min(120, Math.round(v))) : 30 }),
  setAnimateSourceStillPath: (p) => set({ animateSourceStillPath: p }),
  setAnimateDialogOpen: (open) => set({ animateDialogOpen: open }),
  setCustomThemeColors: (primary, secondary, bg) =>
    set({ customPrimary: primary, customSecondary: secondary, customBg: bg, theme: "custom" }),
  setCustomUiModalOpen: (open) => set({ customUiModalOpen: open }),
  setAspectRatioLock: (v) => set({ aspectRatioLock: v }),
  setAspectRatio: (ratio) => set({ aspectRatio: ratio }),
  setInPoint: (t) =>
    set((state) => {
      const val = t === null ? null : clampFinite(t, 0, state.duration, 0);
      return {
        inPoint: val,
        outPoint:
          state.outPoint !== null && val !== null && state.outPoint <= val ? null : state.outPoint,
      };
    }),
  setOutPoint: (t) =>
    set((state) => {
      const val = t === null ? null : clampFinite(t, 0, state.duration, 0);
      return {
        outPoint: val,
        inPoint:
          state.inPoint !== null && val !== null && state.inPoint >= val ? null : state.inPoint,
      };
    }),
  clearInOut: () => set({ inPoint: null, outPoint: null }),
  setExportProgress: (progress) => set({ exportProgress: clampFinite(progress, 0, 100, 0) }),
  setExportIsRunning: (v) => set({ exportIsRunning: v }),
  requestExportCancel: () => set({ exportCancelRequested: true }),
  triggerExport: () => set((state) => ({ exportTriggerId: state.exportTriggerId + 1 })),
  resetExport: () =>
    set({ exportProgress: 0, exportIsRunning: false, exportCancelRequested: false }),
  setWatermark: (settings) => set((state) => ({ watermark: { ...state.watermark, ...settings } })),
  clearStack: () =>
    set((state) => ({
      ...pushHistory(state),
      effectStack: [],
      selectedStackId: null,
    })),
  replaceStack: (stack) =>
    set((state) => ({
      ...pushHistory(state),
      effectStack: stack,
      selectedStackId: null,
    })),

  undo: () =>
    set((state) => {
      if (state.pastStacks.length === 0) return state;
      const newPast = [...state.pastStacks];
      const previous = newPast.pop()!;
      return {
        pastStacks: newPast,
        futureStacks: [state.effectStack, ...state.futureStacks],
        effectStack: previous,
      };
    }),

  redo: () =>
    set((state) => {
      if (state.futureStacks.length === 0) return state;
      const newFuture = [...state.futureStacks];
      const next = newFuture.shift()!;
      return {
        pastStacks: [...state.pastStacks, state.effectStack],
        futureStacks: newFuture,
        effectStack: next,
      };
    }),

  canUndo: () => get().pastStacks.length > 0,
  canRedo: () => get().futureStacks.length > 0,

  // Audio actions
  setAudioEnabled: (v) => set({ audioEnabled: v }),
  setAudioFilePath: (path) => set({ audioFilePath: path }),
  setAudioPlaying: (v) => set({ audioPlaying: v }),
  setAudioVolume: (v) => set({ audioVolume: clampFinite(v, 0, 1, 0) }),
  setAudioBpm: (bpm) => set({ audioBpm: bpm }),
  setAudioBandEnergies: (bands) => set({ audioBandEnergies: bands }),
  setAudioBeatFlags: (flags) => set({ audioBeatFlags: flags }),
  setAudioBinding: (stackId, paramId, binding) =>
    set((state) => {
      const entryBindings = { ...(state.audioBindings[stackId] || {}) };
      if (binding) {
        entryBindings[paramId] = binding;
      } else {
        delete entryBindings[paramId];
      }
      return {
        audioBindings: { ...state.audioBindings, [stackId]: entryBindings },
      };
    }),
  setAudioBindings: (bindings) => set({ audioBindings: bindings }),
  setAudioMappedValues: (values) => set({ audioMappedValues: values }),
  setAudioBakeData: (data) => set({ audioBakeData: data }),
  setAudioManifest: (manifest) => set({ audioManifest: manifest }),
  setAudioManifestProgress: (progress, phase) =>
    set({ audioManifestProgress: progress, audioManifestPhase: phase }),
  setAudioIsSilent: (silent) => set({ audioIsSilent: silent }),

  addKeyframe: (stackId, paramId, keyframe) =>
    set((state) => {
      const entry = state.keyframes[stackId] || {};
      const track = entry[paramId] ? [...entry[paramId]] : [];
      track.push(keyframe);
      track.sort((a, b) => a.time - b.time);
      return { keyframes: { ...state.keyframes, [stackId]: { ...entry, [paramId]: track } } };
    }),

  removeKeyframe: (stackId, paramId, keyframeId) =>
    set((state) => {
      const entry = state.keyframes[stackId];
      if (!entry) return state;
      const track = entry[paramId];
      if (!track) return state;
      const filtered = track.filter((k) => k.id !== keyframeId);
      const newEntry = { ...entry };
      if (filtered.length === 0) delete newEntry[paramId];
      else newEntry[paramId] = filtered;
      const newKeyframes = { ...state.keyframes };
      if (Object.keys(newEntry).length === 0) delete newKeyframes[stackId];
      else newKeyframes[stackId] = newEntry;
      return { keyframes: newKeyframes };
    }),

  updateKeyframe: (stackId, paramId, keyframeId, patch) =>
    set((state) => {
      const entry = state.keyframes[stackId];
      if (!entry) return state;
      const track = entry[paramId];
      if (!track) return state;
      const updated = track.map((k) => (k.id === keyframeId ? { ...k, ...patch } : k));
      updated.sort((a, b) => a.time - b.time);
      return { keyframes: { ...state.keyframes, [stackId]: { ...entry, [paramId]: updated } } };
    }),

  setKeyframesForTrack: (stackId, paramId, keyframes) =>
    set((state) => {
      const entry = state.keyframes[stackId] || {};
      const sorted = [...keyframes].sort((a, b) => a.time - b.time);
      return { keyframes: { ...state.keyframes, [stackId]: { ...entry, [paramId]: sorted } } };
    }),

  setKeyframes: (keyframes) => set({ keyframes }),

  clearKeyframes: (stackId, paramId) =>
    set((state) => {
      if (!stackId) return { keyframes: {} };
      const newKeyframes = { ...state.keyframes };
      if (paramId && newKeyframes[stackId]) {
        const entry = { ...newKeyframes[stackId] };
        delete entry[paramId];
        if (Object.keys(entry).length === 0) delete newKeyframes[stackId];
        else newKeyframes[stackId] = entry;
      } else delete newKeyframes[stackId];
      return { keyframes: newKeyframes };
    }),

  getKeyframeValue: (stackId, paramId, time) => {
    const state = get();
    const entry = state.keyframes[stackId];
    if (!entry) return null;
    const track = entry[paramId];
    if (!track || track.length === 0) return null;
    let idx = 0;
    while (idx < track.length && track[idx].time < time) idx++;
    if (idx < track.length && track[idx].time === time) return track[idx].value;
    if (idx === 0) return track[0].value;
    if (idx >= track.length) return track[track.length - 1].value;
    const k1 = track[idx - 1];
    const k2 = track[idx];
    const t = (time - k1.time) / (k2.time - k1.time);
    const eased = applyEasing(t, k1.easing);
    return k1.value + (k2.value - k1.value) * eased;
  },

  // Mask actions
  setActiveMask: (maskB64) =>
    set((state) => ({ activeMask: maskB64, maskRevision: state.maskRevision + 1 })),
  setMaskVisible: (v) => set({ maskVisible: v }),
  toggleViewportGuide: (guide) =>
    set((state) => ({
      viewportGuides: { ...state.viewportGuides, [guide]: !state.viewportGuides[guide] },
    })),
  setViewportGuides: (guides) =>
    set((state) => ({ viewportGuides: { ...state.viewportGuides, ...guides } })),
  setMaskTab: (tab) => set({ maskTab: tab }),
  setMaskTool: (tool) => set({ maskTool: tool }),
  setBrushSize: (size) => set({ brushSize: clampFinite(size, 1, 200, 20) }),
  setSam3Ready: (v) => set({ sam3Ready: v }),
  setSam3ImageLoaded: (v) => set({ sam3ImageLoaded: v }),
  setSam3Mode: (mode) => set({ sam3Mode: mode }),
  setSam3Clicking: (v) => set({ sam3Clicking: v }),

  // Tree masking actions
  addSam3Point: (point) => set((state) => ({ sam3Points: [...state.sam3Points, point] })),
  removeSam3Point: (index) =>
    set((state) => ({ sam3Points: state.sam3Points.filter((_, i) => i !== index) })),
  clearSam3Points: () => set({ sam3Points: [] }),
  setSam3HoverMask: (mask) => set({ sam3HoverMask: mask }),
  setSam3OverlayOpacity: (v) => set({ sam3OverlayOpacity: v }),
  setSam3OverlayColor: (color) => set({ sam3OverlayColor: color }),

  // Multi-mask actions
  setSam3Masks: (masks, scores) => {
    // masks[0] becomes activeMask below and flows straight into the WebGL
    // mask-texture loader (EffectChain.getMaskTexture), which awaits an
    // <img> load with no other validation. An empty or malformed entry here
    // -- e.g. a partial/edge-case response from the SAM3 subprocess -- used
    // to reach that loader unfiltered and could hang it forever (img.src=""
    // often fires neither onload nor onerror), freezing the live preview.
    // Filtering at this boundary, where the IPC response becomes trusted
    // app state, means every caller is protected without each one having to
    // remember to check.
    const paired = masks.map((m, i) => [m, scores[i]] as const).filter(([m]) => !!m);
    if (paired.length < masks.length) {
      console.warn(
        `setSam3Masks: dropped ${masks.length - paired.length} empty/invalid mask candidate(s) from SAM3 response`
      );
    }
    const validMasks = paired.map(([m]) => m);
    const validScores = paired.map(([, s]) => s);
    set((state) => ({
      sam3Masks: validMasks,
      sam3MaskScores: validScores,
      sam3MaskIndex: 0,
      activeMask: validMasks.length > 0 ? validMasks[0] : null,
      maskRevision: state.maskRevision + 1,
    }));
  },
  setSam3MaskIndex: (index) =>
    set((state) => {
      const safeIndex = Math.max(0, Math.min(state.sam3Masks.length - 1, index));
      return {
        sam3MaskIndex: safeIndex,
        activeMask: state.sam3Masks[safeIndex] ?? null,
        maskRevision: state.maskRevision + 1,
      };
    }),

  setSam3FrameMasks: (masks) =>
    set((state) => ({ sam3FrameMasks: masks, maskRevision: state.maskRevision + 1 })),
  clearSam3FrameMasks: () =>
    set((state) => ({ sam3FrameMasks: {}, maskRevision: state.maskRevision + 1 })),

  // Proxy actions
  setProxyEnabled: (v) => set({ proxyEnabled: v }),
  setProxyPath: (path) => set({ proxyPath: path }),
  setProxyMaxWidth: (w) => set({ proxyMaxWidth: w }),
  setProxyCrf: (crf) => set({ proxyCrf: crf }),
  setProxyGenerating: (v) => set({ proxyGenerating: v }),

  // Track actions
  addTrack: (name) => {
    const id = nextStackId("track");
    const track: Track = {
      id,
      name: name || `Track ${get().tracks.length + 1}`,
      visible: true,
      opacity: 1,
      blendMode: "normal",
      effectStack: [],
      filePath: null,
    };
    set((state) => ({
      tracks: [...state.tracks, track],
      activeTrackId: id,
    }));
    return id;
  },

  removeTrack: (id) =>
    set((state) => ({
      tracks: state.tracks.filter((t) => t.id !== id),
      activeTrackId: state.activeTrackId === id ? null : state.activeTrackId,
    })),

  renameTrack: (id, name) =>
    set((state) => ({
      tracks: state.tracks.map((t) => (t.id === id ? { ...t, name } : t)),
    })),

  setActiveTrack: (id) => set({ activeTrackId: id }),

  setTrackVisible: (id, visible) =>
    set((state) => ({
      tracks: state.tracks.map((t) => (t.id === id ? { ...t, visible } : t)),
    })),

  setTrackOpacity: (id, opacity) =>
    set((state) => ({
      tracks: state.tracks.map((t) =>
        t.id === id ? { ...t, opacity: Math.max(0, Math.min(1, opacity)) } : t
      ),
    })),

  setTrackBlendMode: (id, mode) =>
    set((state) => ({
      tracks: state.tracks.map((t) => (t.id === id ? { ...t, blendMode: mode } : t)),
    })),

  moveTrack: (fromIndex, toIndex) =>
    set((state) => {
      const tracks = [...state.tracks];
      if (fromIndex < 0 || fromIndex >= tracks.length || toIndex < 0 || toIndex >= tracks.length) {
        return {};
      }
      const [moved] = tracks.splice(fromIndex, 1);
      tracks.splice(toIndex, 0, moved);
      return { tracks };
    }),

  getActiveTrack: () => {
    const state = get();
    return state.tracks.find((t) => t.id === state.activeTrackId) ?? null;
  },
}));

/** Easing function for keyframe interpolation */
export function applyEasing(t: number, easing: EasingType): number {
  if (easing === "hold") return 0;
  // Clamp t to [0, 1] to prevent out-of-range values from NaN/Infinity/negative inputs
  const tc = Number.isNaN(t) ? 0 : Math.max(0, Math.min(1, t));
  if (easing === "linear") return tc;
  if (easing === "easeIn") return tc * tc;
  if (easing === "easeOut") return 1 - (1 - tc) * (1 - tc);
  // easeInOut
  return tc < 0.5 ? 2 * tc * tc : 1 - Math.pow(-2 * tc + 2, 2) / 2;
}
