pub mod atkinson;
pub mod auto_palette;
pub mod bayer;
pub mod bayer_tables;
pub mod blue_noise;
pub mod burkes;
pub mod custom_matrix;
pub mod error_diffusion;
pub mod error_diffusion_variants;
pub mod floyd_steinberg;
pub mod halftone;
pub mod jarvis_judice_ninke;
pub mod kmeans;
pub mod line_screen;
pub mod ordered_dither_variants;
pub mod palette_dither;
pub mod random_noise;
pub mod riemersma;
pub mod sierra;
pub mod stucki;
pub mod threshold;

pub use atkinson::AtkinsonDither;
pub use auto_palette::AutoPaletteDither;
pub use bayer::BayerDither;
pub use blue_noise::BlueNoiseDither;
pub use burkes::BurkesDither;
pub use custom_matrix::CustomMatrixDither;
pub use error_diffusion_variants::ErrorDiffusionDither;
pub use floyd_steinberg::FloydSteinbergDither;
pub use halftone::HalftoneDither;
pub use jarvis_judice_ninke::JarvisJudiceNinke;
pub use kmeans::KMeansDither;
pub use line_screen::LineScreen;
pub use ordered_dither_variants::OrderedDitherVariants;
pub use palette_dither::PaletteDither;
pub use random_noise::RandomNoiseDither;
pub use riemersma::RiemersmaDither;
pub use sierra::SierraDither;
pub use stucki::StuckiDither;
pub use threshold::ThresholdDither;

#[cfg(test)]
mod output_stability_tests;
