# MoshDither Studio — Worktree Task Creator
# Creates an isolated Git worktree for a development task.
# Usage: pwsh -File scripts/new-task.ps1 -TaskName "auth-system"

param(
    [Parameter(Mandatory=$true)]
    [string]$TaskName,

    [string]$WorktreeRoot = (Join-Path (Split-Path $PSScriptRoot) "worktrees")
)

$ErrorActionPreference = "Stop"

# Sanitize task name
$safeName = $TaskName -replace '[^a-zA-Z0-9_-]', '-'
$timestamp = Get-Date -Format "yyyyMMdd-HHmmss"
$branchName = "session/$timestamp-$safeName"

# Derive deterministic port from branch name hash (range 3100-9999)
$hashBytes = [System.Text.Encoding]::UTF8.GetBytes($branchName)
$sha = [System.Security.Cryptography.SHA256]::Create()
$hash = $sha.ComputeHash($hashBytes)
$portSeed = [BitConverter]::ToUInt16($hash, 0)
$port = 3100 + ($portSeed % 6900)

# Create worktree directory
$worktreePath = Join-Path $WorktreeRoot "$timestamp-$safeName"
if (-not (Test-Path $WorktreeRoot)) {
    New-Item -ItemType Directory -Path $WorktreeRoot -Force | Out-Null
}

Write-Host "`n=== MoshDither Studio — New Task Worktree ===" -ForegroundColor Cyan
Write-Host "Task:     $TaskName"
Write-Host "Branch:   $branchName"
Write-Host "Port:     $port"
Write-Host "Path:     $worktreePath`n"

# Create the branch and worktree
git worktree add -b $branchName $worktreePath 2>&1
if ($LASTEXITCODE -ne 0) {
    Write-Host "ERROR: Failed to create worktree" -ForegroundColor Red
    exit 1
}

# Copy .env.example as local .env
$envExample = Join-Path $PSScriptRoot ".." ".env.example"
$envTarget = Join-Path $worktreePath ".env"
if (Test-Path $envExample) {
    Copy-Item $envExample $envTarget
    # Inject the deterministic port
    Add-Content $envTarget "`n# Auto-generated by new-task.ps1"
    Add-Content $envTarget "VITE_DEV_SERVER_PORT=$port"
    Write-Host "Copied .env.example -> .env (port=$port)" -ForegroundColor Green
}

Write-Host "`n=== Worktree Ready ===" -ForegroundColor Green
Write-Host "  cd $worktreePath"
Write-Host "  npm run dev -- --port $port"
Write-Host "  npm run tauri:dev`n"
